### ISSUE TITLE
Support replaying projections / views

### ISSUE THREAD

**Issue by nowakprojects** [johanhaleby/occurrent#60]
It would be nice to automate replaying projections / views created with subscriptions.

**Comment by johanhaleby** [comment]
Hi!

I think this is possible already, but it can be a bit cumbersome :). All subscriptions take a `StartAt` parameter, for example when using MongoDB, you can do:

```kotlin
subscriptions.subscribe("mySubscriptionId", StartAt.subscriptionPosition(MongoOperationTimeSubscriptionPosition(BsonTimeStamp(0))) { event ->
 ...
}
```

This will start the subscription from the earliest position available in the MongoDB oplog. Of course, this is MongoDB specific so we should probably come up with something better. But speaking of oplog, MongoDB can run out of oplog and thus you can't use the oplog to start from the beginning. For this reason, I've created a utility called "catch-up subscription" (see [here](https://occurrent.org/documentation#catch-up-subscription-blocking)) whose responsibility is to read from the event store to catch-up with the current position of a subscription and then automatically switch over to listen to new events. Today, this is what you _should_ use in Occurrent to achieve what you're asking. Here's an example:

```kotlin
@Bean
fun catchupSubscriptionModel(storage: SubscriptionPositionStorage, mongoTemplate: MongoTemplate, eventStoreQueries: EventStoreQueries): SubscriptionModel {
    val mongoSubscriptionModel = SpringMongoSubscriptionModel(mongoTemplate, EVENTS_COLLECTION_NAME, TimeRepresentation.DATE)
    val durableSubscriptionModel = DurableSubscriptionModel(mongoSubscriptionModel, storage)
    return CatchupSubscriptionModel(
        durableSubscriptionModel, eventStoreQueries,
        CatchupSubscriptionModelConfig(useSubscriptionPositionStorage(storage))
    )
}
```

A catch-up subscription will wrap a subscription model but before using it, it'll start replaying all historic events. Once the subscription has caught up it will not replay again but just continue from the current position (if the position has been persisted to the `SubscriptionPositionStorage`). You can see an example [here](https://github.com/johanhaleby/occurrent/tree/master/example/domain/word-guessing-game/mongodb/spring/blocking/src/main/kotlin/org/occurrent/example/domain/wordguessinggame/mongodb/spring/blocking) (in the `Bootstrap.kt` class).

The catch-up subscription module also contains on implementation of `SubscriptionPosition`called `TimeBasedSubscriptionPosition` that you can use like this:

```kotlin
subscriptions.subscribe("mySubscriptionId", StartAt.subscriptionPosition(TimeBasedSubscriptionPosition beginningOfTime())) { event ->
 ...
}
```

or 

```kotlin
subscriptions.subscribe("mySubscriptionId", StartAt.subscriptionPosition(TimeBasedSubscriptionPosition.form(OffsetDateTime.now().minusDays(3))) { event ->
 ...
}
```

Maybe this class should be moved outside of the `catchup-subscription` module to avoid users having to do `MongoOperationTimeSubscriptionPosition(BsonTimeStamp(0))`. But,  I'm not entirely sure since it can be misleading (at least for mongodb) since there's no way, that I know of, to _know_ if MongoDB has enough oplog to actually accommodate the request. If there's not enough oplog available, it will just start from the begging of the oplog that is present (which might not contain the first event!) and you won't get an error (see my [stackoverflow question](https://stackoverflow.com/questions/63860124/how-to-check-if-theres-enough-oplog-history-for-a-change-stream-start-position)).

**Comment by johanhaleby** [comment]
Maybe we should rename "CatchupSubscription" to "ReplaySubscription"?

**Comment by nowakprojects** [comment]
Thank you for the answer, yes, so it's possible to replay with occurrent :) 
The name is also accurate, because for example EventStoreDB use the same term for probably the same concept:
https://developers.eventstore.com/clients/dotnet/5.0/subscriptions/catchup-subscriptions.html#subscribing-to-a-stream

**Comment by johanhaleby** [comment]
Oh, I wasn't aware that catchup subscription was "the" canonical term for this (didn't know that eventstoredb called it that as well). But that's encouraging! Thanks for the pointer.
